"""empty message

Revision ID: 0346920ef870
Revises: 2d1b13c85e6d
Create Date: 2020-07-06 10:29:02.587610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0346920ef870'
down_revision = '2d1b13c85e6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tgl', 'concept')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tgl', sa.Column('concept', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
