"""empty message

Revision ID: 1f6bcaa1f620
Revises: e3c17a95da1a
Create Date: 2020-06-01 16:40:32.793784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6bcaa1f620'
down_revision = 'e3c17a95da1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscalcalendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('week_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fiscalcalendar')
    # ### end Alembic commands ###
