"""empty message

Revision ID: 2d1b13c85e6d
Revises: ce73c30f050c
Create Date: 2020-07-06 10:16:54.829537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1b13c85e6d'
down_revision = 'ce73c30f050c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderaccuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tgl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('week_of_month', sa.Integer(), nullable=True),
    sa.Column('week_of_year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('concept', sa.String(length=15), nullable=True),
    sa.Column('location', sa.String(length=15), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('number_measured', sa.Integer(), nullable=True),
    sa.Column('number_passed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tgl')
    op.drop_table('orderaccuracy')
    # ### end Alembic commands ###
