"""empty message

Revision ID: 43a557b2eaaf
Revises: 55d7065caf27
Create Date: 2020-06-17 10:14:20.411483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43a557b2eaaf'
down_revision = '55d7065caf27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamefilm', 'tm_name')
    op.add_column('tacotimes', sa.Column('concept', sa.String(length=20), nullable=True))
    op.add_column('tacotimes', sa.Column('fiscal_month', sa.String(length=20), nullable=True))
    op.add_column('tacotimes', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('tacotimes', sa.Column('quarter', sa.Integer(), nullable=True))
    op.add_column('tacotimes', sa.Column('time_in_seconds', sa.Integer(), nullable=True))
    op.add_column('tacotimes', sa.Column('week_of_month', sa.Integer(), nullable=True))
    op.add_column('tacotimes', sa.Column('week_of_year', sa.Integer(), nullable=True))
    op.drop_column('tacotimes', 'time_measure')
    op.drop_column('tacotimes', 'fiscal_week')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tacotimes', sa.Column('fiscal_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tacotimes', sa.Column('time_measure', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('tacotimes', 'week_of_year')
    op.drop_column('tacotimes', 'week_of_month')
    op.drop_column('tacotimes', 'time_in_seconds')
    op.drop_column('tacotimes', 'quarter')
    op.drop_column('tacotimes', 'fiscal_year')
    op.drop_column('tacotimes', 'fiscal_month')
    op.drop_column('tacotimes', 'concept')
    op.add_column('gamefilm', sa.Column('tm_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
