"""empty message

Revision ID: 55d7065caf27
Revises: 1f6bcaa1f620
Create Date: 2020-06-11 15:28:14.382439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d7065caf27'
down_revision = '1f6bcaa1f620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamefilm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('week_of_month', sa.Integer(), nullable=True),
    sa.Column('week_of_year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('concept', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('tm_name', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamefilm')
    # ### end Alembic commands ###
