"""empty message

Revision ID: 63df98b5ccd2
Revises: 81a1a6ac01d4
Create Date: 2020-05-07 02:23:41.610886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63df98b5ccd2'
down_revision = '81a1a6ac01d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodvariance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamefilm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('tm_name', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('time_measure', sa.DateTime(timezone=40), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orderaccuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storeassessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tgl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('time_measure', sa.DateTime(timezone=40), nullable=True),
    sa.Column('tm_name', sa.String(length=50), nullable=True),
    sa.Column('score', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tgl')
    op.drop_table('storeassessments')
    op.drop_table('orderaccuracy')
    op.drop_table('inspections')
    op.drop_table('gamefilm')
    op.drop_table('foodvariance')
    # ### end Alembic commands ###
