"""empty message

Revision ID: 6da3f9a02ce5
Revises: baa48167aa05
Create Date: 2020-07-21 08:56:53.284695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6da3f9a02ce5'
down_revision = 'baa48167aa05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bagtimes', 'time_in_seconds')
    op.drop_column('bagtimes', 'date_measured')
    op.drop_column('bagtimes', 'concept_month_avg')
    op.drop_column('bagtimes', 'concept')
    op.drop_column('bagtimes', 'concept_quarter_avg')
    op.drop_column('bagtimes', 'concept_week_avg')
    op.drop_column('bagtimes', 'score_met')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bagtimes', sa.Column('score_met', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bagtimes', sa.Column('concept_week_avg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bagtimes', sa.Column('concept_quarter_avg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bagtimes', sa.Column('concept', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('bagtimes', sa.Column('concept_month_avg', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bagtimes', sa.Column('date_measured', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bagtimes', sa.Column('time_in_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
