"""empty message

Revision ID: 76da881ecf02
Revises: a1b92ca395ba
Create Date: 2020-05-26 09:47:38.532436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76da881ecf02'
down_revision = 'a1b92ca395ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('quarter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'quarter')
    # ### end Alembic commands ###
