"""empty message

Revision ID: 7c32d7cd12b7
Revises: 43a557b2eaaf
Create Date: 2020-06-22 19:35:25.160852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c32d7cd12b7'
down_revision = '43a557b2eaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bagtimes', sa.Column('concept', sa.String(length=20), nullable=True))
    op.add_column('bagtimes', sa.Column('date_measured', sa.Date(), nullable=True))
    op.add_column('bagtimes', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('bagtimes', sa.Column('quarter', sa.Integer(), nullable=True))
    op.add_column('bagtimes', sa.Column('time_in_seconds', sa.Integer(), nullable=True))
    op.add_column('bagtimes', sa.Column('week_of_month', sa.Integer(), nullable=True))
    op.add_column('bagtimes', sa.Column('week_of_year', sa.Integer(), nullable=True))
    op.drop_column('bagtimes', 'score')
    op.drop_column('bagtimes', 'fiscal_week')
    op.drop_column('bagtimes', 'month_ending')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bagtimes', sa.Column('month_ending', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bagtimes', sa.Column('fiscal_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bagtimes', sa.Column('score', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('bagtimes', 'week_of_year')
    op.drop_column('bagtimes', 'week_of_month')
    op.drop_column('bagtimes', 'time_in_seconds')
    op.drop_column('bagtimes', 'quarter')
    op.drop_column('bagtimes', 'fiscal_year')
    op.drop_column('bagtimes', 'date_measured')
    op.drop_column('bagtimes', 'concept')
    # ### end Alembic commands ###
