"""empty message

Revision ID: 7dea4c120569
Revises: cccb3b4fc3c6
Create Date: 2020-06-22 19:41:20.143893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dea4c120569'
down_revision = 'cccb3b4fc3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bagtimes', sa.Column('concept_month_avg', sa.Integer(), nullable=True))
    op.add_column('bagtimes', sa.Column('concept_quarter_avg', sa.Integer(), nullable=True))
    op.add_column('bagtimes', sa.Column('concept_week_avg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bagtimes', 'concept_week_avg')
    op.drop_column('bagtimes', 'concept_quarter_avg')
    op.drop_column('bagtimes', 'concept_month_avg')
    # ### end Alembic commands ###
