"""empty message

Revision ID: 81a1a6ac01d4
Revises: c1cac5f4191d
Create Date: 2020-03-16 16:26:53.194549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a1a6ac01d4'
down_revision = 'c1cac5f4191d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('week_of_month', sa.Integer(), nullable=True),
    sa.Column('week_of_year', sa.Integer(), nullable=True),
    sa.Column('concept', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=15), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('bbq_sales', sa.Float(), nullable=True),
    sa.Column('taco_sales', sa.Float(), nullable=True),
    sa.Column('group_meal_sales', sa.Float(), nullable=True),
    sa.Column('mavn_sales', sa.Float(), nullable=True),
    sa.Column('doordash_sales', sa.Float(), nullable=True),
    sa.Column('total_guest_count', sa.Integer(), nullable=True),
    sa.Column('bbq_guest_count', sa.Integer(), nullable=True),
    sa.Column('taco_guest_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
