"""empty message

Revision ID: 98cd57283c3d
Revises: e7c3e5fce303
Create Date: 2020-03-10 11:52:51.183321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cd57283c3d'
down_revision = 'e7c3e5fce303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ce', sa.Column('fiscal_month', sa.String(length=20), nullable=True))
    op.add_column('ce', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ce', 'fiscal_year')
    op.drop_column('ce', 'fiscal_month')
    # ### end Alembic commands ###
