"""empty message

Revision ID: a1b92ca395ba
Revises: df52956da77e
Create Date: 2020-05-13 21:17:48.447938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b92ca395ba'
down_revision = 'df52956da77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ce', sa.Column('week_of_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ce', 'week_of_month')
    # ### end Alembic commands ###
