"""empty message

Revision ID: a3fcda8b02ac
Revises: 0346920ef870
Create Date: 2020-07-16 13:10:45.414115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3fcda8b02ac'
down_revision = '0346920ef870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderaccuracy', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('orderaccuracy', sa.Column('inaccurate_count', sa.Integer(), nullable=True))
    op.add_column('orderaccuracy', sa.Column('quarter', sa.Integer(), nullable=True))
    op.add_column('orderaccuracy', sa.Column('week_ending', sa.Date(), nullable=True))
    op.add_column('orderaccuracy', sa.Column('week_of_month', sa.Integer(), nullable=True))
    op.add_column('orderaccuracy', sa.Column('week_of_year', sa.Integer(), nullable=True))
    op.drop_column('orderaccuracy', 'score')
    op.drop_column('orderaccuracy', 'month_ending')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderaccuracy', sa.Column('month_ending', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('orderaccuracy', sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('orderaccuracy', 'week_of_year')
    op.drop_column('orderaccuracy', 'week_of_month')
    op.drop_column('orderaccuracy', 'week_ending')
    op.drop_column('orderaccuracy', 'quarter')
    op.drop_column('orderaccuracy', 'inaccurate_count')
    op.drop_column('orderaccuracy', 'fiscal_year')
    # ### end Alembic commands ###
