"""empty message

Revision ID: baa48167aa05
Revises: a3fcda8b02ac
Create Date: 2020-07-16 15:32:12.345516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa48167aa05'
down_revision = 'a3fcda8b02ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderaccuracy', sa.Column('concept', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderaccuracy', 'concept')
    # ### end Alembic commands ###
