"""empty message

Revision ID: c1cac5f4191d
Revises: 98cd57283c3d
Create Date: 2020-03-12 13:40:49.617319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cac5f4191d'
down_revision = '98cd57283c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ce', sa.Column('mod_one', sa.String(length=50), nullable=True))
    op.add_column('ce', sa.Column('mod_two', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ce', 'mod_two')
    op.drop_column('ce', 'mod_one')
    # ### end Alembic commands ###
