"""empty message

Revision ID: cccb3b4fc3c6
Revises: 7c32d7cd12b7
Create Date: 2020-06-22 19:39:46.335985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccb3b4fc3c6'
down_revision = '7c32d7cd12b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bagtimes', sa.Column('month_avg', sa.Integer(), nullable=True))
    op.add_column('bagtimes', sa.Column('quarter_avg', sa.Integer(), nullable=True))
    op.add_column('bagtimes', sa.Column('week_avg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bagtimes', 'week_avg')
    op.drop_column('bagtimes', 'quarter_avg')
    op.drop_column('bagtimes', 'month_avg')
    # ### end Alembic commands ###
