"""empty message

Revision ID: ce73c30f050c
Revises: 7dea4c120569
Create Date: 2020-07-06 10:15:15.344300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce73c30f050c'
down_revision = '7dea4c120569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tgl')
    op.drop_table('orderaccuracy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderaccuracy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('month_ending', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fiscal_month', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('score', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='orderaccuracy_pkey')
    )
    op.create_table('tgl',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_ending', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fiscal_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_measured', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time_measure', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tm_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('score', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tgl_pkey')
    )
    # ### end Alembic commands ###
