"""empty message

Revision ID: df52956da77e
Revises: 63df98b5ccd2
Create Date: 2020-05-11 12:33:56.494376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df52956da77e'
down_revision = '63df98b5ccd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('concept', sa.String(length=15), nullable=True))
    op.add_column('inspections', sa.Column('fiscal_month', sa.String(length=20), nullable=True))
    op.add_column('inspections', sa.Column('fiscal_year', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('week_of_month', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('week_of_year', sa.Integer(), nullable=True))
    op.drop_column('inspections', 'fiscal_week')
    op.drop_column('inspections', 'time_measure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('time_measure', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('inspections', sa.Column('fiscal_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('inspections', 'week_of_year')
    op.drop_column('inspections', 'week_of_month')
    op.drop_column('inspections', 'fiscal_year')
    op.drop_column('inspections', 'fiscal_month')
    op.drop_column('inspections', 'concept')
    # ### end Alembic commands ###
