"""empty message

Revision ID: e3c17a95da1a
Revises: 76da881ecf02
Create Date: 2020-06-01 14:40:39.310617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c17a95da1a'
down_revision = '76da881ecf02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscalcalendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('fiscal_month', sa.Integer(), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('week_of_month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gamefilm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamefilm',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week_ending', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fiscal_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('date_measured', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tm_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='gamefilm_pkey')
    )
    op.drop_table('fiscalcalendar')
    # ### end Alembic commands ###
