"""empty message

Revision ID: e7c3e5fce303
Revises: 
Create Date: 2020-02-25 13:58:59.575216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c3e5fce303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bagtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('month_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_month', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('score', sa.DateTime(timezone=40), nullable=True),
    sa.Column('score_met', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('tm_name', sa.String(length=50), nullable=True),
    sa.Column('tm_sales', sa.Float(), nullable=True),
    sa.Column('tm_minutes', sa.Integer(), nullable=True),
    sa.Column('tm_efficiency', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gmtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('time_measure', sa.DateTime(timezone=40), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linetimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('am_taken', sa.Integer(), nullable=True),
    sa.Column('am_out', sa.Integer(), nullable=True),
    sa.Column('am_over_11', sa.Integer(), nullable=True),
    sa.Column('pm_taken', sa.Integer(), nullable=True),
    sa.Column('pm_out', sa.Integer(), nullable=True),
    sa.Column('pm_over_11', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tacotimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=True),
    sa.Column('fiscal_week', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('date_measured', sa.Date(), nullable=True),
    sa.Column('time_measure', sa.DateTime(timezone=40), nullable=True),
    sa.Column('score', sa.DateTime(timezone=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tacotimes')
    op.drop_table('linetimes')
    op.drop_table('gmtimes')
    op.drop_table('ce')
    op.drop_table('bagtimes')
    # ### end Alembic commands ###
